config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Authentication Page
  devise_for :users, skip: %i[confirmation unlock passwords]

  # Front
  root to: 'front/home#index'
  resources :posts, only: %i[index show], controller: 'front/posts'

  # Admin
  devise_scope :user do
    namespace :admin do
      root to: 'dashboard#index'
      resources :posts
      resources :users
    end
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id               :bigint           not null, primary key
#  title            :string           not null
#  slug             :string           not null
#  excerpt          :string
#  content          :text
#  published        :boolean
#  published_at     :datetime
#  meta_keywords    :string
#  meta_description :text
#  author_id        :bigint
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  belongs_to :author, class_name: 'User', inverse_of: :posts

  validates :title, presence: true, length: { minimum: 3 }
  validates :excerpt, presence: true, length: { minimum: 20 }
  validates :content, presence: true, length: { minimum: 40 }
  validates :published_at, presence: true, if: :published

  delegate :name, :email, to: :author, prefix: true

  default_scope {  order(published_at: :desc) }
  scope :reversed, -> { order(published_at: :asc) }
  scope :published, -> { where(published: true) }

  def self.permitted_attributes
    [
      :title,
      :excerpt,
      :content,
      :published,
      :published_at,
      :meta_keywords,
      :meta_description,
    ]
  end

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < BaseController
    load_and_authorize_resource

    before_action :find_post, except: %i[index new create]

    def index
      @posts = include_author
    end

    def new
      @post = current_user.posts.new
    end

    def create
      @post = current_user.posts.new(post_params)

      if @post.save
        flash[:notice] = 'Post has been created'
        redirect_to admin_posts_path
      else
        flash[:error] = @post.errors.full_messages.first
        render :new
      end
    end

    def show; end

    def edit; end

    def update
      if @post.update(post_params)
        flash[:notice] = 'Post has been updated'
        redirect_to admin_post_path(@post)
      else
        flash[:error] = @post.errors.full_messages.first
        render :edit
      end
    end

    def destroy
      if @post.destroy
        flash[:notice] = 'Post has been deleted'
      else
        flash[:error] = @post.errors.full_messages.first
      end

      redirect_to admin_posts_path
    end

    private

    def include_author
      collection = if current_user.admin?
        Post.includes(:author)
      else
        current_user.posts
      end

      collection
    end

    def post_params
      params.require(:post).permit(*Post.permitted_attributes)
    end

    def find_post
      @post = include_author.friendly.find(params[:id])
    end
  end
end

app/controllers/front/base_controller.rb
module Front
  class BaseController < ActionController::Base
    layout 'front'
  end
end

app/controllers/front/home_controller.rb
module Front
  class HomeController < BaseController

    def index
      @posts = Post.includes(:author).published.limit(5)
      @older_than = 1
      if Post.published.offset(5 * @older_than).count == 0
        @older_than = nil
      end
    end
  end
end

app/controllers/front/posts_controller.rb
module Front
  class PostsController < BaseController

    def index
      page = params[:page].to_i rescue 0

      @posts = Post.includes(:author).published.limit(5).offset(5 * page)

      @newer_than = page.zero? ? nil : page - 1
      @older_than = page + 1
      if Post.published.offset(5 * @older_than).count == 0
        @older_than = nil
      end
    end

    def show
      @post = Post.friendly.find(params[:id])
    end
  end
end

app/views/front/posts/_collection.html.erb
<!-- Post preview-->
<%= render partial: 'front/posts/post', collection: posts, as: :post %>
<div class="<%= 'btn-toolbar ' if newer_than%>justify-content-between">
  <!-- Pager-->
  <%- if newer_than -%>
  <div class="d-flex justify-content-start mb-4">
    <%= link_to(posts_path(page: newer_than), class: 'btn btn-primary text-uppercase') do %>
      &laquo; Newer Posts
    <% end %>
  </div>
  <% end %>

  <%- if older_than -%>
  <div class="d-flex justify-content-end mb-4">
    <%= link_to(posts_path(page: older_than), class: 'btn btn-primary text-uppercase') do %>
      Older Posts &raquo;
    <% end %>
  </div>
  <%- end -%>
</div>

app/views/front/posts/_post.html.erb
<div class="post-preview">
  <%= link_to(post_path(post)) do %>
    <h2 class="post-title"><%= post.title %></h2>
    <h3 class="post-subtitle"><%= post.meta_description %></h3>
  <% end %>
  <p class="post-meta">
    Posted by
    <a href="#!"><%= post.author_name %></a>
    on <%= l(post.published_at, format: :short) %>
    </p>
</div>
<!-- Divider-->
<hr class="my-4" />

app/views/front/posts/index.html.erb
<header class="masthead" style="background-image: url('<%= image_path('about-bg.jpg') %>');">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Main Content-->
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <%= render partial: 'front/posts/collection',
                   locals: { posts: @posts,
                             newer_than: @newer_than,
                             older_than: @older_than } %>
    </div>
  </div>
</div>

app/views/front/posts/show.html.erb
<% content_for :title, @post.title %>
<% content_for :meta_keywords, @post.meta_keywords %>
<% content_for :meta_description, @post.meta_description %>
<% content_for :author_name, @post.author_name %>

<header class="masthead" style="background-image: url('<%= image_path('post-bg.jpg') %>');">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="post-heading">
          <h1><%= @post.title %></h1>
          <h2 class="subheading"><%= @post.excerpt %></h2>
          <span class="meta">
            Posted by
            <a href="#!"><%= @post.author_name %></a>
            on <%= l(@post.published_at, format: :short) %>
          </span>
        </div>
      </div>
    </div>
  </div>
</header>

<!-- Post Content-->
<article class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <%= @post.content.html_safe %>
      </div>
    </div>
  </div>
</article>