config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Authentication Page
  devise_for :users, skip: %i[confirmation unlock passwords]

  # Front
  root to: 'front/home#index'
  resources :posts, only: %i[index show], controller: 'front/posts'

  # Admin
  devise_scope :user do
    namespace :admin do
      root to: 'dashboard#index'
      resources :posts
      resources :users
    end
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id               :bigint           not null, primary key
#  title            :string           not null
#  slug             :string           not null
#  excerpt          :string
#  content          :text
#  published        :boolean
#  published_at     :datetime
#  meta_keywords    :string
#  meta_description :text
#  author_id        :bigint
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  belongs_to :author, class_name: 'User', inverse_of: :posts

  validates :title, presence: true, length: { minimum: 3 }
  validates :excerpt, presence: true, length: { minimum: 20 }
  validates :content, presence: true, length: { minimum: 40 }
  validates :published_at, presence: true, if: :published

  delegate :name, :email, to: :author, prefix: true

  default_scope {  order(published_at: :desc) }
  scope :reversed, -> { order(published_at: :asc) }
  scope :published, -> { where(published: true) }

  def self.permitted_attributes
    [
      :title,
      :excerpt,
      :content,
      :published,
      :published_at,
      :meta_keywords,
      :meta_description,
    ]
  end

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < BaseController
    load_and_authorize_resource

    before_action :find_post, except: %i[index new create]

    def index
      @posts = include_author
    end

    def new
      @post = current_user.posts.new
    end

    def create
      @post = current_user.posts.new(post_params)

      if @post.save
        flash[:notice] = 'Post has been created'
        redirect_to admin_posts_path
      else
        flash[:error] = @post.errors.full_messages.first
        render :new
      end
    end

    def show; end

    def edit; end

    def update
      if @post.update(post_params)
        flash[:notice] = 'Post has been updated'
        redirect_to admin_post_path(@post)
      else
        flash[:error] = @post.errors.full_messages.first
        render :edit
      end
    end

    def destroy
      if @post.destroy
        flash[:notice] = 'Post has been deleted'
      else
        flash[:error] = @post.errors.full_messages.first
      end

      redirect_to admin_posts_path
    end

    private

    def include_author
      collection = if current_user.admin?
        Post.includes(:author)
      else
        current_user.posts
      end

      collection
    end

    def post_params
      params.require(:post).permit(*Post.permitted_attributes)
    end

    def find_post
      @post = include_author.friendly.find(params[:id])
    end
  end
end

app/controllers/front/posts_controller.rb
module Front
  class PostsController < BaseController

    def index
      page = params[:page].to_i rescue 0

      @posts = Post.includes(:author).published.limit(5).offset(5 * page)

      @newer_than = page.zero? ? nil : page - 1
      @older_than = page + 1
      if Post.published.offset(5 * @older_than).count == 0
        @older_than = nil
      end
    end

    def show
      @post = Post.friendly.find(params[:id])
    end
  end
end

app/views/admin/posts/_form.html.erb
<%= flash_message(resource: form.object) %>

<div class="form-group">
  <%= form.label :title, class: 'small mb-1' %>
  <%= form.text_field :title, class: 'form-control py-2', placeholder: 'Title' %>
</div>
<div class="form-group">
  <%= form.label :excerpt, class: 'small mb-1' %>
  <%= form.text_field :excerpt, class: 'form-control py-2', placeholder: 'Excerpt' %>
</div>
<div class="form-group">
  <%= form.label :content, class: 'small mb-1' %>
  <%= form.text_area :content, class: 'form-control py-2', placeholder: 'Content' %>
</div>
<div class="form-group">
  <%= form.label :published_at, class: 'small mb-1' %>
  <%= form.datetime_field :published_at, class: 'form-control py-2' %>
</div>
<div class="form-group">
  <%= form.label :meta_keywords, class: 'small mb-1' %>
  <%= form.text_field :meta_keywords, class: 'form-control py-2', placeholder: 'keyword, keyword, keyword' %>
</div>
<div class="form-group">
  <%= form.label :meta_description, class: 'small mb-1' %>
  <%= form.text_area :meta_description, class: 'form-control py-2', placeholder: 'Description' %>
</div>

<div class="d-flex align-items-center justify-content-between">
  <div class="form-group">
    <div class="form-check">
      <%= form.check_box :published, class: 'form-check-input' %>
      <%= form.label :published, class: 'form-check-label' %>
    </div>
  </div>
  <div class="form-group">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
</div>

app/views/admin/posts/edit.html.erb
<% content_for :model_title, @post.title %>
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item">
    <%= link_to('Posts', admin_posts_path) %>
  </li>
  <li class="breadcrumb-item">
    <%= link_to(@post.title, admin_post_path(@post)) %>
  </li>
  <li class="breadcrumb-item active">Edit</li>
<% end %>
<%= form_with model: [:admin, @post], method: :put do |form| %>
  <%= render partial: 'admin/posts/form', locals: { form: form } %>
<% end %>

app/views/admin/posts/index.html.erb
<% content_for :model_title, 'Posts' %>
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item active">Posts</li>
<% end %>
<%= flash_message %>
<div class="d-flex justify-content-end mb-4">
  <%= link_to(new_admin_post_path, class: 'btn btn-primary') do %>
    <i class="fas fa-plus"></i> Create Post
  <% end %>
</div>
<div class="card mb-4">
  <div class="card-header">
    <i class="fas fa-table mr-1"></i>
    List of Posts
  </div>
  <div class="card-body">
    <table id="datatables" class="table table-bordered" width="100%" cellspacing="0">
      <thead>
        <tr>
          <th>Title</th>
          <th>Author</th>
          <th>Published</th>
          <th>Published at</th>
          <th></th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <th>Title</th>
          <th>Author</th>
          <th>Published</th>
          <th>Published at</th>
          <th></th>
        </tr>
      </tfoot>
      <tbody>
        <% if @posts.empty? %>
        <tr>
          <td class="dataTables-empty" colspan="5">No entries found</td>
        </tr>
        <% end %>
        <% @posts.each do |post| %>
        <tr>
          <td><strong><%= post.title %></strong></td>
          <td><%= link_to(post.author_name, admin_user_path(post.author), class: "btn btn-link")%></td>
          <td><i class="fas fa-<%= post.published? ? 'check' : 'times' %>"></i></td>
          <td><%= l(post.published_at, format: :short) if post.published_at %></td>
          <td>
            <div class="d-flex justify-content-around align-items-center">
              <span class="border border-primary">
              <%= link_to(admin_post_path(post)) do %>
                <i class="fas fa-info"></i>
              <% end %>
              </span>
              &nbsp;
              &nbsp;
              <span class="border border-primary">
              <%= link_to(edit_admin_post_path(post)) do %>
                <i class="fas fa-edit"></i>
              <% end %>
              </span>
              &nbsp;
              &nbsp;
              <span class="border border-danger">
              <%= link_to(admin_post_path(post),
                          class: 'text-danger',
                          data: { method: :delete, confirm: 'Are you sure?' }) do %>
                <i class="fas fa-trash"></i>
              <% end %>
              </span>
            </div>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/posts/new.html.erb
<% content_for :model_title, 'New Post' %>
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item">
    <%= link_to('Posts', admin_posts_path) %>
  </li>
  <li class="breadcrumb-item active">New</li>
<% end %>
<%= form_with model: [:admin, @post], method: :post do |form| %>
  <%= render partial: 'admin/posts/form', locals: { form: form } %>
<% end %>

app/views/admin/posts/show.html.erb
<% content_for :model_title, @post.title %>
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item">
    <%= link_to('Post', admin_posts_path) %>
  </li>
  <li class="breadcrumb-item active"><%= @post.title %></li>
<% end %>
<%= flash_message %>
<div class="d-flex justify-content-end mb-4">
  <%= link_to(edit_admin_post_path(@post), class: 'btn btn-primary') do %>
    <i class="fas fa-edit"></i> Edit Post
  <% end %>
</div>
<dl class="row">
  <dt class="col-sm-3">Published ?</dt>
  <dd class="col-sm-9"><i class="fas fa-<%= @post.published? ? 'check' : 'times' %>"></i></dd>
  <dt class="col-sm-3">Published at</dt>
  <dd class="col-sm-9"><%= l(@post.published_at, format: :short) if @post.published_at %></dd>
  <dt class="col-sm-3">Title</dt>
  <dd class="col-sm-9"><%= @post.title %></dd>
  <dt class="col-sm-3">Excerpt</dt>
  <dd class="col-sm-9"><%= @post.excerpt %></dd>
  <dt class="col-sm-3">Content</dt>
  <dd class="col-sm-9"><%= @post.content %></dd>
  <dt class="col-sm-3">Meta Keywords</dt>
  <dd class="col-sm-9"><%= @post.meta_keywords.presence || '-' %></dd>
  <dt class="col-sm-3">Meta Description</dt>
  <dd class="col-sm-9"><%= @post.meta_description.presence || '-' %></dd>
</dl>