config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Authentication Page
  devise_for :users, skip: %i[confirmation unlock passwords]

  # Front
  root to: 'front/home#index'
  resources :posts, only: %i[index show], controller: 'front/posts'

  # Admin
  devise_scope :user do
    namespace :admin do
      root to: 'dashboard#index'
      resources :posts
      resources :users
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :bigint           not null, primary key
#  email               :string           default(""), not null
#  encrypted_password  :string           default(""), not null
#  remember_created_at :datetime
#  sign_in_count       :integer          default(0), not null
#  current_sign_in_at  :datetime
#  last_sign_in_at     :datetime
#  current_sign_in_ip  :string
#  last_sign_in_ip     :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  name                :string           not null
#  role                :string           default("regular_user")
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :recoverable,:confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable, :rememberable,
         :validatable

  ROLES = {
    admin: 'admin',
    regular_user: 'regular_user'
  }.freeze

  enum role: ROLES

  has_many :posts, dependent: :destroy, inverse_of: :author, foreign_key: 'author_id'

  validates :name, presence: true
  validates :role, inclusion: { in: User.roles.keys }

  before_validation :ensure_role, on: :create

  def self.permitted_attributes
    [
      :name,
      :role
    ]
  end

  private

  def ensure_role
    self.role = ROLES[:regular_user] unless role
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < BaseController
    load_and_authorize_resource

    before_action :find_user, except: %i[index new create]

    def index
      @users = User.all
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(create_params)

      if @user.save
        flash[:notice] = 'User has been created'
        redirect_to admin_users_path
      else
        flash[:error] = @user.errors.full_messages.first
        render :new
      end
    end

    def show; end

    def edit; end

    def update
      # blank password
      if update_params[:password].blank?
        update_params.delete("password")
        update_params.delete("password_confirmation")
      end

      if @user.update(update_params)
        flash[:notice] = 'User has been updated'
        redirect_to admin_user_path(@user)
      else
        flash[:error] = @user.errors.full_messages.first
        render :edit
      end
    end

    def destroy
      if @user.destroy
        flash[:notice] = 'User has been deleted'
      else
        flash[:error] = @user.errors.full_messages.first
      end

      redirect_to admin_users_path
    end

    private

    def create_params
      params.require(:user).permit(*User.permitted_attributes+[:email, :password, :password_confirmation])
    end

    def update_params
      params.require(:user).permit(*User.permitted_attributes+[:email])
    end

    def find_user
      @user = User.find(params[:id])
    end
  end
end

app/views/admin/users/_form.html.erb
<%= flash_message(resource: form.object) %>

<div class="form-group">
  <%= form.label :name, class: 'small mb-1' %>
  <%= form.text_field :name, class: 'form-control py-2', placeholder: 'Name' %>
</div>
<div class="form-group">
  <%= form.label :email, class: 'small mb-1' %>
  <%= form.email_field :email, class: 'form-control py-2', placeholder: 'Email' %>
</div>
<div class="form-group">
  <%= form.label :role, class: 'small mb-1' %>
  <%= form.select :role, User.roles.keys, { }, { class: 'form-select' } %>
</div>
<div class="form-group">
  <%= form.label :password, class: 'small mb-1' %>
  <%= form.password_field :password, class: 'form-control py-2' %>
  <%= "<i>(leave blank if you don't want to change it)</i>" if form.object.persisted? %>
</div>
<div class="form-group">
  <%= form.label :password_confirmation, class: 'small mb-1' %>
  <%= form.password_field :password_confirmation, class: 'form-control py-2' %>
</div>

<div class="d-flex align-items-center justify-content-end">
  <div class="form-group">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
</div>

app/views/admin/users/edit.html.erb
<% content_for :model_title, @user.name %>
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item">
    <%= link_to('Users', admin_users_path) %>
  </li>
  <li class="breadcrumb-item">
    <%= link_to(@user.name, admin_user_path(@user)) %>
  </li>
  <li class="breadcrumb-item active">Edit</li>
<% end %>
<%= form_with model: [:admin, @user], method: :put do |form| %>
  <%= render partial: 'admin/users/form', locals: { form: form } %>
<% end %>

app/views/admin/users/index.html.erb
<% content_for :model_title, 'Users' %>
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item active">Users</li>
<% end %>
<%= flash_message %>
<div class="d-flex justify-content-end mb-4">
  <%= link_to(new_admin_user_path, class: 'btn btn-primary') do %>
    <i class="fas fa-plus"></i> Create User
  <% end %>
</div>
<div class="card mb-4">
  <div class="card-header">
    <i class="fas fa-table mr-1"></i>
    List of Users
  </div>
  <div class="card-body">
    <table id="datatables" class="table table-bordered" width="100%" cellspacing="0">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Role</th>
          <th>Last Sign in at</th>
          <th></th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Role</th>
          <th>Last Sign in at</th>
          <th></th>
        </tr>
      </tfoot>
      <tbody>
        <% if @users.empty? %>
        <tr>
          <td class="dataTables-empty" colspan="5">No entries found</td>
        </tr>
        <% end %>
        <% @users.each do |user| %>
        <tr>
          <td><strong><%= user.name %></strong></td>
          <td><%= user.email %></td>
          <td><%= t(user.role, scope: :user_role) %></td>
          <td><%= l(user.last_sign_in_at, format: :short) if user.last_sign_in_at %></td>
          <td>
            <div class="d-flex justify-content-around align-items-center">
              <span class="border border-primary">
              <%= link_to(admin_user_path(user), class: "border") do %>
                <i class="fas fa-info"></i>
              <% end %>
              </span>
              &nbsp;
              &nbsp;
              <span class="border border-primary">
              <%= link_to(edit_admin_user_path(user)) do %>
                <i class="fas fa-edit"></i>
              <% end %>
              </span>
              &nbsp;
              &nbsp;
              <%= content_tag(:span, class: "border border-danger") do %>
                <%= link_to(admin_user_path(user),
                        class: 'text-danger',
                        data: { method: :delete, confirm: 'Are you sure?' }) do %>
                <i class="fas fa-trash"></i>
                <% end %>
              <% end if user.id != 1 %>
              </span>
            </div>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/new.html.erb
<% content_for :model_title, 'New User' %>
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item">
    <%= link_to('Users', admin_users_path) %>
  </li>
  <li class="breadcrumb-item active">New</li>
<% end %>
<%= form_with model: [:admin, @user], method: :post do |form| %>
  <%= render partial: 'admin/users/form', locals: { form: form } %>
<% end %>

app/views/admin/users/show.html.erb
<% content_for :model_title, @user.name %>
<% content_for :breadcrumb do %>
  <li class="breadcrumb-item">
    <%= link_to('User', admin_users_path) %>
  </li>
  <li class="breadcrumb-item active"><%= @user.name %></li>
<% end %>
<%= flash_message %>
<div class="d-flex justify-content-end mb-4">
  <%= link_to(edit_admin_user_path(@user), class: 'btn btn-primary') do %>
    <i class="fas fa-edit"></i> Edit User
  <% end %>
</div>
<dl class="row">
  <dt class="col-sm-3">Email</dt>
  <dd class="col-sm-9"><%= @user.email %></dd>
  <dt class="col-sm-3">Name</dt>
  <dd class="col-sm-9"><%= @user.name %></dd>
  <dt class="col-sm-3">Role</dt>
  <dd class="col-sm-9"><%= t(@user.role, scope: :user_role) %></dd>
  <dt class="col-sm-3">Last Sign in IP</dt>
  <dd class="col-sm-9"><%= @user.last_sign_in_ip %></dd>
  <dt class="col-sm-3">Last Sign in at</dt>
  <dd class="col-sm-9"><%= l(@user.last_sign_in_at, format: :short) if @user.last_sign_in_at %></dd>
</dl>